# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@types/prop-types-15.7.1" = {
      name = "_at_types_slash_prop-types";
      packageName = "@types/prop-types";
      version = "15.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/prop-types/-/prop-types-15.7.1.tgz";
        sha512 = "CFzn9idOEpHrgdw8JsoTkaDDyRWk1jrzIV8djzcgpq0y9tG4B4lFT+Nxh52DVpDXV+n4+NPNv7M1Dj5uMp6XFg==";
      };
    };
    "@types/react-16.8.17" = {
      name = "_at_types_slash_react";
      packageName = "@types/react";
      version = "16.8.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react/-/react-16.8.17.tgz";
        sha512 = "pln3mgc6VfkNg92WXODul/ONo140huK9OMsx62GlBlZ2lvjNK86PQJhYMPLO1i66aF5O9OPyZefogvNltBIszA==";
      };
    };
    "@types/react-dom-16.8.4" = {
      name = "_at_types_slash_react-dom";
      packageName = "@types/react-dom";
      version = "16.8.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react-dom/-/react-dom-16.8.4.tgz";
        sha512 = "eIRpEW73DCzPIMaNBDP5pPIpK1KXyZwNgfxiVagb5iGiz6da+9A5hslSX6GAQKdO7SayVCS/Fr2kjqprgAvkfA==";
      };
    };
    "csstype-2.6.4" = {
      name = "csstype";
      packageName = "csstype";
      version = "2.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-2.6.4.tgz";
        sha512 = "lAJUJP3M6HxFXbqtGRc0iZrdyeN+WzOWeY0q/VnFzI+kqVrYIzC7bWlKqCW7oCIdzoPkvfp82EVvrTlQ8zsWQg==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "prop-types-15.7.2" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.7.2.tgz";
        sha512 = "8QQikdH7//R2vurIJSutZ1smHYTcLpRWEOlHnzcWHmBYrOGUysKwSsrC89BCiFj3CbrfJ/nXFdJepOVrY1GCHQ==";
      };
    };
    "react-16.8.6" = {
      name = "react";
      packageName = "react";
      version = "16.8.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-16.8.6.tgz";
        sha512 = "pC0uMkhLaHm11ZSJULfOBqV4tIZkx87ZLvbbQYunNixAAvjnC+snJCg0XQXn9VIsttVsbZP/H/ewzgsd5fxKXw==";
      };
    };
    "react-dom-16.8.6" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "16.8.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-16.8.6.tgz";
        sha512 = "1nL7PIq9LTL3fthPqwkvr2zY7phIPjYrT0jp4HjyEQrEROnw4dG41VVwi/wfoCneoleqrNX7iAD+pXebJZwrwA==";
      };
    };
    "react-is-16.8.6" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.8.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.8.6.tgz";
        sha512 = "aUk3bHfZ2bRSVFFbbeVS4i+lNPZr3/WM5jT2J5omUVV1zzcs1nAaf3l51ctA5FFvCRbhrH0bdAsRRQddFJZPtA==";
      };
    };
    "scheduler-0.13.6" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.13.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.13.6.tgz";
        sha512 = "IWnObHt413ucAYKsD9J1QShUKkbKLQQHdxRyw73sw4FN26iWr3DY/H34xGPe4nmL1DwXyWmSWmMrA9TfQbE/XQ==";
      };
    };
  };
  args = {
    name = "javascript-demo";
    packageName = "javascript-demo";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."@types/prop-types-15.7.1"
      sources."@types/react-16.8.17"
      sources."@types/react-dom-16.8.4"
      sources."csstype-2.6.4"
      sources."js-tokens-4.0.0"
      sources."loose-envify-1.4.0"
      sources."object-assign-4.1.1"
      sources."prop-types-15.7.2"
      sources."react-16.8.6"
      sources."react-dom-16.8.6"
      sources."react-is-16.8.6"
      sources."scheduler-0.13.6"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "JavaScript Demo Project";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}